name: Foo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  spotify_playlist_convert:
    runs-on: ubuntu-latest
    steps:
      - name: Start container
        run: |
          echo "running container..."
      - name: ASdf
        run: |
          docker --help
